### ISSUE TITLE
PKGBUILD: add xorg-xinput as dependency

### ISSUE THREAD

**Issue by malteroemer** [AnatolyRugalev/libinput-xrandr-autorotate#1]
When trying to run without xinput I get the following error:

```
> Executing command: xinput list --name-only

> Error: exec: "xinput": executable file not found in $PATH
Cannot autodetect touchscreens: exec: "xinput": executable file not found in $PATH
```

**Comment by AnatolyRugalev** [comment]
Thank you for the report.

Actually I didn't expect anyone to use this hacky app. Sure, gonna update dependencies in AUR shortly

**Comment by AnatolyRugalev** [comment]
Fixed with https://github.com/AnatolyRugalev/libinput-xrandr-autorotate/commit/9f8be89064bf21b136452acca970ff34af7372d0
